# Original from envoyproject/envoy:examples/front-proxy/docker-compose.yml
# Modified by Instana:
# - use instana-opentracing dockerfiles
version: '2'
services:

  test-app:
    build:
      context: .
    networks:
      - databasemesh
    environment:
      - INSTANA_DEV=1
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
#      - LOGGING_LEVEL_ROOT=DEBUG
    ports:
      - "8080:8080"
    expose:
      - "8080"

  database:
    image: postgres:11-alpine
    restart: always
    networks:
      - databasemesh
    environment:
      - POSTGRES_PASSWORDPOSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  agent:
    image: instana/agent:test
    pid: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
    networks:
      databasemesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=saas-us-west-2.instana.io
      - INSTANA_AGENT_ENDPOINT_PORT=443
      - INSTANA_AGENT_KEY=<FILL ME UP>
      - INSTANA_AGENT_ZONE=bad-sql-world
    expose:
      - "42699"

networks:
  databasemesh: {}
